version: '3.7'
services:
  postgres:
    image: postgres:alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-airflow}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-airflow}
      - POSTGRES_DB=${POSTGRES_DB:-airflow}

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-gil@udacity.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-qwerty123}
    depends_on:
      - postgres
    ports:
      - "80:80"

  jupyter:
    image: jupyter/scipy-notebook
    environment:
      NB_UID: ${NB_UID:-1000}
      JUPYTER_TOKEN: ${JUPYTER_TOKEN:-udacity}
    user: root
    volumes:
      - ./notebooks:/home/jovyan/work
    ports:
      - "8888:8888"

  webserver:
    image: godatadriven/airflow:latest
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER:-airflow}:${POSTGRES_PASSWORD:-airflow}@postgres:5432/${POSTGRES_DB:-airflow}
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - WAIT_FOR=postgres:5432
    depends_on:
      - postgres
    volumes:
      - ./dags:/root/airflow/dags
      - ./plugins:/root/airflow/plugins
      - ./logs:/root/airflow/logs
      - ./environment.yml:/dependencies/environment.yml
    ports:
      - "8080:8080"
    command: upgradedb_webserver

  scheduler:
    image: godatadriven/airflow:latest
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER:-airflow}:${POSTGRES_PASSWORD:-airflow}@postgres:5432/${POSTGRES_DB:-airflow}
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - WAIT_FOR=webserver:8080
    depends_on:
      - webserver
    volumes:
      - ./dags:/root/airflow/dags
      - ./plugins:/root/airflow/plugins
      - ./logs:/root/airflow/logs
      - ./environment.yml:/dependencies/environment.yml
    command: scheduler