name: DEND-Capstone
channels:
  - conda-forge
  - defaults
dependencies:
  - airflow=1.10.3post2
  - alembic=0.9.9
  - asn1crypto=0.24.0
  - babel=2.7.0
  - bzip2=1.0.8
  - ca-certificates=2019.6.16
  - certifi=2019.6.16
  - cffi=1.12.3
  - chardet=3.0.4
  - click=7.0
  - colorama=0.4.1
  - configparser=3.5.0
  - croniter=0.3.30
  - cryptography=2.7
  - defusedxml=0.5.0
  - dill=0.2.9
  - flask=1.1.1
  - flask-admin=1.5.3
  - flask-appbuilder=1.12.3
  - flask-babel=0.12.2
  - flask-caching=1.3.3
  - flask-login=0.4.1
  - flask-openid=1.2.5
  - flask-sqlalchemy=2.4.0
  - flask-swagger=0.2.13
  - flask-wtf=0.14.2
  - future=0.16.0
  - gitdb2=2.0.5
  - gitpython=2.1.13
  - gunicorn=19.9.0
  - icu=64.2
  - idna=2.8
  - iso8601=0.1.12
  - itsdangerous=1.1.0
  - jinja2=2.10
  - json-merge-patch=0.2
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=8.0.0
  - libcxxabi=8.0.0
  - libffi=3.2.1
  - libgfortran=4.0.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libopenblas=0.3.6
  - libxml2=2.9.9
  - libxslt=1.1.32
  - lockfile=0.12.2
  - lxml=4.4.0
  - mako=1.1.0
  - markdown=2.6.11
  - markupsafe=1.1.1
  - ncurses=6.1
  - numpy=1.17.0
  - openssl=1.1.1c
  - pandas=0.25.0
  - pendulum=1.4.4
  - pip=19.2.1
  - psutil=5.6.3
  - pycparser=2.19
  - pygments=2.4.2
  - pyopenssl=19.0.0
  - pysocks=1.7.0
  - python=3.7.3
  - python-daemon=2.1.2
  - python-dateutil=2.8.0
  - python-editor=1.0.4
  - python-nvd3=0.15.0
  - python-slugify=1.2.6
  - python3-openid=3.1.0
  - pytz=2019.2
  - pytzdata=2019.2
  - pyyaml=5.1.2
  - readline=8.0
  - requests=2.22.0
  - setproctitle=1.1.10
  - setuptools=41.0.1
  - six=1.12.0
  - smmap2=2.0.5
  - sqlalchemy=1.2.18
  - sqlite=3.29.0
  - tabulate=0.8.3
  - tenacity=4.12.0
  - text-unidecode=1.2
  - thrift=0.11.0
  - tk=8.6.9
  - tzlocal=2.0.0
  - unicodecsv=0.14.1
  - unidecode=1.1.1
  - urllib3=1.25.3
  - werkzeug=0.15.5
  - wheel=0.33.4
  - wtforms=2.2.1
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
  - zope.deprecation=4.4.0

